ApManBundle\Entity\Device:
  type: entity
  table: device
  manyToOne:
    radio:
      targetEntity: Radio
      inversedBy: devices
      cascade: [ persist ]
      joinColumn:
        name: radio_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
    ssid:
      targetEntity: SSID
      inversedBy: devices
      cascade: [ persist ]
      joinColumn:
        name: ssid_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
    config:
      type: array
      nullable: true

