ApManBundle\Entity\Radio:
  type: entity
  table: radio
  manyToOne:
    accesspoint:
      targetEntity: AccessPoint
      inversedBy: radios
      joinColumn:
        name: accesspoint_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
  oneToMany:
    devices:
      targetEntity: Device
      mappedBy: radio
      cascade: [ persist ]
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
    config_type:
      type: string
      nullable: true
      length: 64
    config_path:
      type: string
      nullable: true
      length: 64
    config_disabled:
      type: string
      nullable: true
      length: 1
    config_channel:
      type: string
      nullable: true
      length: 4
    config_channel_list:
      type: string
      nullable: true
      length: 64
    config_hwmode:
      type: string
      nullable: true
      length: 64
    config_txpower:
      type: string
      nullable: true
      length: 64
    config_country:
      type: string
      nullable: true
      length: 64
    config_require_mode:
      type: string
      nullable: true
      length: 64
    config_log_level:
      type: string
      nullable: true
      length: 64
    config_htmode:
      type: string
      nullable: true
      length: 64
    config_noscan:
      type: string
      nullable: true
      length: 64
    config_beacon_int:
      type: string
      nullable: true
      length: 64
    config_basic_rate:
      type: string
      nullable: true
      length: 64
    config_supported_rates:
      type: string
      nullable: true
      length: 64
    config_rts:
      type: string
      nullable: true
      length: 64
    config_antenna_gain:
      type: string
      nullable: true
      length: 64
    config_ht_capab:
      type: array
      nullable: true

