ApManBundle\Entity\SSID:
  type: entity
  table: ssid
  oneToMany:
    config_options:
      targetEntity: SSIDConfigOption
      mappedBy: ssid
      cascade: [ persist ]
    config_lists:
      targetEntity: SSIDConfigList
      mappedBy: ssid
      cascade: [ persist ]
    config_files:
      targetEntity: SSIDConfigFile
      mappedBy: ssid
      cascade: [ persist ]
    devices:
      targetEntity: Device
      mappedBy: ssid
      cascade: [ persist ]
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
      length: 64
