ApManBundle\Entity\SSIDConfigFile:
  type: entity
  table: ssid_config_file
  manyToOne:
    ssid:
      targetEntity: SSID
      inversedBy: config_files
      joinColumn:
        name: ssid_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
      cascade: [ persist ]
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
    filename:
      type: string
      nullable: true
    content:
      type: text
      nullable: true
