ApManBundle\Entity\SSIDConfigOption:
  type: entity
  table: ssid_config_option
  manyToOne:
    ssid:
      targetEntity: SSID
      inversedBy: config_options
      joinColumn:
        name: ssid_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
      cascade: [ persist ]
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
    value:
      type: string
      nullable: true
