ApManBundle\Entity\SSIDConfigList:
  type: entity
  table: ssid_config_list
  oneToMany:
    options:
      targetEntity: SSIDConfigListOption
      mappedBy: ssid_config_list
  manyToOne:
    ssid:
      targetEntity: SSID
      inversedBy: config_lists
      joinColumn:
        name: ssid_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
        onUpdate: CASCADE
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: true
