ApManBundle\Entity\Syslog:
  type: entity
  table: syslog
  id:
    id:
      type: integer
      primary: true
      generator:
        strategy: AUTO
  fields:
    ts:
      type: datetime
    source:
      type: string
      nullable: false
      length: 64
    message:
      type: text
      nullable: false
      length: 4096
